export const defaultOptions = {
    autoCloseBrackets: true,
    autoCloseTags: true,
    autofocus: true,
    foldGutter: true,
    gutters: ['CodeMirror-linenumbers', 'CodeMirror-foldgutter'],
    indentWithTabs: true,
    indentUnit: 4,
    tabSize: 4,
    lineWrapping: true,
    lint: true,
    theme: 'rdark',
    lineNumbers: true,
    viewportMargin: Infinity,
}
